/**
 * vim: set ts=4 :
 * ===============================================================
 * SourceMod (C)2004-2007 AlliedModders LLC.  All rights reserved.
 * ===============================================================
 *
 *  This file is part of the SourceMod/SourcePawn SDK.  This file may only be used 
 * or modified under the Terms and Conditions of its License Agreement, which is found 
 * in LICENSE.txt.  The Terms and Conditions for making SourceMod extensions/plugins 
 * may change at any time.  To view the latest information, see:
 *   http://www.sourcemod.net/license.php
 *
 * Version: $Id$
 */
 
#if defined _version_included
 #endinput
#endif
#define _version_included

#define SOURCEMOD_V_MAJOR		1
#define SOURCEMOD_V_MINOR		0
#define SOURCEMOD_V_RELEASE		0

#define SOURCEMOD_VERSION		"1.0.0.577"
