blank_issues_enabled: false
contact_links:
  - name: AlliedModders Discord
    url: https://discord.gg/HUc67zN
    about: General support or assistance
  - name: AlliedModders Forums
    url: https://forums.alliedmods.net
    about: General support or assistance
