#ifndef _INCLUDE_SOURCEMOD_VERSION_H_
#define _INCLUDE_SOURCEMOD_VERSION_H_

#define SOURCEMOD_VERSION	"1.0.0.0"
#define SOURCEMOD_V_MAJOR	1
#define SOURCEMOD_V_MINOR	0
#define SOURCEMOD_V_REV		0
#define SOURCEMOD_V_BUILD	0

#endif //_INCLUDE_SOURCEMOD_VERSION_H_
