/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_REVISION			0
#define SVN_REVISION_STRING		"$trunk"

#endif //_INCLUDE_SVN_VERSION_H_
