/** This file is autogenerated by build scripts */

#ifndef _INCLUDE_SVN_VERSION_H_
#define _INCLUDE_SVN_VERSION_H_

#define SVN_REVISION			399
#define SVN_REVISION_STRING	"399"
#define SVN_FILE_VERSION		1,0,0,399

#endif //_INCLUDE_SVN_VERSION_H_

