/**
 * Autogenerated by build scripts
 */

#ifndef _INCLUDE_GEOIP_VERSION_H_
#define _INCLUDE_GEOIP_VERSION_H_


#define SVN_FULL_VERSION	"1.0.0.431"
#define SVN_FILE_VERSION	1,0,0,431

#endif //_INCLUDE_GEOIP_VERSION_H_
