name: SourceMod clang-4.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'recursive'
    - name: Install System Dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-4.0 g++-multilib lib32z1 lib32z1-dev libc6-dev-i386 libc6-i386
    - name: Install Project Dependencies
      run: cd .. && $GITHUB_WORKSPACE/tools/checkout-deps.sh
    - name: Configure SourceMod
      run: |
        export CC=clang-4.0 && export CXX=clang++-4.0
        mkdir build && cd build
        python ../configure.py --enable-optimize --sdks=episode1,css,tf2,l4d2,csgo,dota
    - name: Build SourceMod
      run: |
        export PATH="~/.local/bin:$PATH"
        cd $GITHUB_WORKSPACE/build
        ambuild
