name: Verify Gamedata
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  verify:
    strategy:
      matrix:
        game: [csgo, tf2, l4d2]
        include:
          - game: csgo
            game_fancy: 'Counter-Strike: Global Offensive'
            game_script: ./scripts/test/csgo.ps1
          - game: cstrike
            game_fancy: 'Counter-Strike: Source'
            game_script ./scripts/test/css.ps1
          - game: dods
            game_fancy: 'Day of Defeat: Source'
            game_script ./scripts/test/dods.ps1
          - game: iosoccer
            game_fancy: 'IOSoccer'
            game_script ./scripts/test/iosoccer.ps1
          - game: tf2
            game_fancy: Team Fortress 2
            game_script: ./scripts/test/tf2.ps1  
          - game: l4d2
            game_fancy: Left 4 Dead 2
            game_script: ./scripts/test/l4d2.ps1
          - game: l4d
            game_fancy: Left 4 Dead
            game_script ./scripts/test/l4d.ps1
          - game: nmrih
            game_fancy: No More Room In Hell
            game_script ./scripts/test/nmrih.ps1
      fail-fast: false
    runs-on: ubuntu-latest
    name: Check ${{ matrix.game_fancy }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Lua 5.1
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"
      - name: Verify Gamedata
        shell: pwsh
        run: ${{ matrix.game_script }} -BASE_PATH:"${{ github.workspace }}" -SUPPRESS_BUILD:$True
      - name: Upload Logs
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: gdc-logs-${{ matrix.game }}
          path: |
            scripts/test/logs