name: Update translation project
on:
  push:
    branches:
      - master
    paths:
      - 'translations/**'
  workflow_dispatch:
jobs:
  update_translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        name: Setup Python 3.10
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        working-directory: tools/language_check
        run: |
          python -m pip install --upgrade -r requirements.txt

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}

      - name: Get project data
        working-directory: tools/language_check
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          ORGANIZATION: alliedmodders
          PROJECT_NUMBER: 1
        run: |
          python ./compare_translation_phrases.py 

